version: 'v1.4.1'

services:
  pdf-tool:
    image: ghcr.io/deskjockey-996/pdf_tools:latest
    container_name: pdf-tool
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./uploads:/app/uploads
      - ./compressed_outputs:/app/compressed_outputs
    restart: unless-stopped